version: '3.8'

services:
    scar-api:
        image: scar-api
        restart: "no"
        environment:
            - DATABASE_HOST=postgresql
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=password
        ports:
            - 3001:3000
        depends_on:
            - postgresql
    postgresql:
        image: postgres
        restart: "no"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - postgresdb:/var/lib/postgresql/data/

volumes:
    postgresdb: